name: flutter_tv_media3
description: "Flutter TV Media3 plugin"

version: 0.0.1
homepage: https://github.com/Farg0k/flutter_tv_media3

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  bloc_event_transformers: ^2.0.0
  intl: ^0.20.2
  collection: ^1.19.1
  sprintf: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pro.appexp.flutter_tv_media3
        pluginClass: FlutterTvMedia3Plugin